Check if the salix-version file is there
Check if the salix-version file is there, before trying to read the
value from it. Bail out with an error message an error code 1 if it
isn't.

diff --git a/reposetup/reposetup b/reposetup/reposetup
--- a/reposetup/reposetup
+++ b/reposetup/reposetup
@@ -63,7 +63,12 @@ checkdefaults(){
 	fi	
 
 	# read salix version
-	version=$( cat $salixtoolsdir/salix-version )
+	if [ -f $salixtoolsdir/salix-version ]; then
+		version=$( cat $salixtoolsdir/salix-version )
+	else
+		echo "ERROR: $salixtoolsdir/salix-version not found"
+		exit 1
+	fi
 
 	CURRENTREPO=""
 
